from TestCommand import testCmd
from ud import ud
from define import define
from weather import weather
from dtc import dtc
from youtube import youtube
from bwotd import bwotd
from help import help
from eightball import eightball
#from google import google